"use client";

import { store } from "@/redux/store";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import NextAuthProvider from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <ToastContainer />
          <NextAuthProvider>{children}</NextAuthProvider>
        </body>
      </html>
    </Provider>
  );
}
